### ISSUE TITLE
user signup: submit form button may cause extra lines and error message to the user if clicked multiple times

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/gsheetsbot#20]
![screen shot 2016-11-21 at 16 35 07](https://cloud.githubusercontent.com/assets/7760/20495496/7d5feb78-b008-11e6-9840-64f6332ef744.png)

![screen shot 2016-11-21 at 16 35 27](https://cloud.githubusercontent.com/assets/7760/20495511/8a174b9a-b008-11e6-951b-d6e0ba1e99a0.png)

**Comment by fczuardi** [comment]
and here is the log:

```
0|bot      | [DEBUG] update =
0|bot      |  {"update_id":184485257,"callback_query":{"id":"83992222413148695","from":{"id":19555963,"first_name":"Fabricio","last_name":"Zuardi","username":"fczuardi"},"message":{"message_id":5258,"from":{"id":284165621,"first_name":"fczdev-sheets","username":"fczdevsheets_bot"},"chat":{"id":19555963,"first_name":"Fabricio","last_name":"Zuardi","username":"fczuardi","type":"private"},"date":1479753157,"text":"Formulário preenchido, quer enviar já ou revisar alguma resposta?"},"chat_instance":"-5519393446415578078","data":"submitUserForm"}}
0|bot      | rowWithUserId [ '19555963' ]
0|bot      | userStatus { userHasApplied: true,
0|bot      |   userStatus: undefined,
0|bot      |   userIsApproved: false,
0|bot      |   statusNote: undefined }
0|bot      | ---writeFormRow--- 83992223645906528
0|bot      | rowWithUserId [ '19555963' ]
0|bot      | userStatus { userHasApplied: true,
0|bot      |   userStatus: undefined,
0|bot      |   userIsApproved: false,
0|bot      |   statusNote: undefined }
0|bot      | ---writeFormRow--- 83992222413148695
0|bot      | { Error: 400: Bad Request: message is not modified
0|bot      |     at buildPayload.then.then.then (/Users/fczuardi/github/gsheetsbot/node_modules/telegraf/lib/network/client.js:74:17)
0|bot      |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
0|bot      |   code: 400,
0|bot      |   description: 'Bad Request: message is not modified',
0|bot      |   retryAfter: undefined,
0|bot      |   migrateToChaId: undefined }
0|bot      | { Error: 400: Bad Request: message is not modified
0|bot      |     at buildPayload.then.then.then (/Users/fczuardi/github/gsheetsbot/node_modules/telegraf/lib/network/client.js:74:17)
0|bot      |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
0|bot      |   code: 400,
0|bot      |   description: 'Bad Request: message is not modified',
0|bot      |   retryAfter: undefined,
0|bot      |   migrateToChaId: undefined }
0|bot      | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|bot      | Error: 400: Bad Request: message is not modified
0|bot      |     at buildPayload.then.then.then (/Users/fczuardi/github/gsheetsbot/node_modules/telegraf/lib/network/client.js:74:17)
0|bot      |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
